Define the Horizon layer and improve the HTTP client implementation.
kommitters/stellar_sdk pull request #14
Opened 2021-11-05 22:47 UTC by juanhurtado10

## Context
The initial structure of this layer does not allow to define other Horizon implementations.

## Objectives
* To properly define the Horizon layer and improve the HTTP client implementation.
* To use canned elixir modules for testing.
* To remove unnecessary dependencies like `mox`.

2021-11-08 22:36 UTC, juanhurtado10 commented
@luishurtado this is ready for review! Thanks.

2021-11-08 23:25 UTC, luishurtado requested changes
Some ideas to consider:

1. Rename `Client.Hackey` to `Client.Default`. Meaning the default implementation will use whatever HTTP Client injected via the `http_client` config variable.
2. The `Horizon.Client.request/5` forwards the invocation to the implementation, so ensure the canned function sends (`send/2`) a message to the current process (the test case, `self()`), then `assert_receive` the message in the test. If the message arrives, the Client is forwarding the call to the implementation; that is all we need to test.

2021-11-08 23:25 UTC, luishurtado commented on lib/horizon/client.ex
> +    if impl, do: impl, else: Client.Hackney
This is a shorter version:

```elixir
Application.get_env(:stellar_sdk, :http_client_impl, Client.Hackney)
```

2021-11-08 23:47 UTC, juanhurtado10 commented
@luishurtado Changes were implemented.

Please let me know if I'm following you on this one! 
> 2\. The `Horizon.Client.request/5` forwards the invocation to the implementation, so ensure the canned function sends (`send/2`) a message to the current process (the test case, `self()`), then `assert_receive` the message in the test. If the message arrives, the Client is forwarding the call to the implementation; that is all we need to test.

2021-11-09 00:26 UTC, luishurtado approved these changes

2021-11-09 00:31 UTC, merged