Change TXBuild Signer new input from tuple to keywordlist
kommitters/stellar_sdk pull request #219
Opened 2022-09-01 20:53 UTC by FelipeGuzmanSierra

Closes #217

## Context
On the protocol 19 implementation, the `TXBuild.Signer.new` method input changed from keyword list to tuple since the key type was inferred from the given key, but is easier for a user to ingest the data with a keyword list, so the old version was added again.

2022-09-01 22:39 UTC, miguelnietoa requested changes
The _expected behavior_ in the issue specifies the `signer_type`, however, it is detected by the `SignerKey` definition, so... these changes seem good! 👏🏻  
But I consider it could have a shorter name like `key`.

@juanhurtado10 could you provide a second review, please?

2022-09-02 01:19 UTC, juanhurtado10 commented on lib/tx_build/signer.ex
> +  def new([{:public_key, signer_key}, {:weight, weight}], _opts) do
What you could get as input is `[ed25519: "XXXXX]` or `[pre_auth_tx: "YYYYY"]` or `[sha256_hash: "ZZZZZ"]`

2022-09-02 13:25 UTC, miguelnietoa commented on lib/tx_build/signer.ex
> +  def new([{:public_key, signer_key}, {:weight, weight}], _opts) do
@FelipeGuzmanSierra Well, let's keep the implementation with the input like this: 
```suggestion
  def new([{signer_type, signer_key}, {:weight, weight}], _opts) do
```

That was already implemented but was changed on this PR, take a look: 
https://github.com/kommitters/stellar_sdk/pull/204/files#diff-022e8adc94d6da4bfaeb2e8d7708b4c9dd8eaf91837752f2bff4a36cbab0b370

2022-09-05 13:25 UTC, miguelnietoa approved these changes

2022-09-05 13:29 UTC, merged